### ISSUE TITLE
教你DIY一个PM2.5检测仪github link broken

### ISSUE THREAD

**Issue by hailinzeng** [nladuo/nladuo.github.io#1]
https://github.com/nladuo/IoT-Firstep/tree/master/code/6.5/BLECom 链接不存在

**Comment by nladuo** [comment]
当时章节更新了一下，应该是[这个](https://github.com/nladuo/IoT-Firstep/tree/master/code/6.6/BLECom)。（之前写博客的笔记本操作系统坏了，等我把数据拷出来之后改一下。）
